version: "3.1"

networks:
    mongo:
        external:
            name: mongo

services:
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        networks:
            - mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: XxusernamexX
            MONGO_INITDB_ROOT_PASSWORD: XxpasswordxX

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        networks:
            - mongo
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: XxusernamexX
            ME_CONFIG_MONGODB_ADMINPASSWORD: XxpasswordxX
        links:
            - mongo
