overwrite: true
schema: 'http://localhost:8000/graphql'
documents: './src/app/shared/graphql/documents/**/*.graphql'
generates:
  ./src/app/shared/graphql/.generated.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-apollo-angular'
config:
  ngModule: src/app/shared/graphql/graphql.module#GraphQLModule
  querySuffix: 'GqlQuery'
  mutationSuffix: 'GqlMutation'
  subscriptionSuffix: 'GqlSubscription'
