overwrite: true
schema: 'http://localhost:8000/graphql'
# documents: "./src/app/shared/graphql/operations/**/*.graphql"
generates:
  ./src/app/shared/graphql/types.d.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-apollo-angular'
config:
  querySuffix: 'QueryGql'
  mutationSuffix: 'MutationGql'
  subscriptionSuffix: 'SubscriptionGql'
