version: "3.1"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: u5ern@me
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
    hostname: mongo.rep
    networks:
      default:
         aliases:
            - mongo.rep
    command:
    - --replSet
    - rep
    # docker exec -i -t mongo mongo mongodb://u5ern%40me:P%40ssw0rd@localhost:27017/test?authSource=admin --eval "rs.initiate();rs.add('mongo2.repl');rs.addArb('mongo3.repl');"
    depends_on:
      - mongo2
      - mongo3
  mongo2:
    image: mongo:latest
    container_name: mongo2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: u5ern@me
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
    hostname: mongo2.rep
    ports:
      - 27018:27017
    networks:
      default:
         aliases:
            - mongo2.rep
    command:
    - --replSet
    - rep
  mongo3:
    image: mongo:latest
    container_name: mongo3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: u5ern@me
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
    hostname: mongo3.rep
    ports:
      - 27019:27017
    networks:
      default:
         aliases:
            - mongo3.rep
    command:
    - --replSet
    - rep
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: u5ern@me
      ME_CONFIG_MONGODB_ADMINPASSWORD: P@ssw0rd
    links:
      - mongo
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: always
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaegertracing
    restart: always
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
